### PR TITLE
Add implicit surface demo.

### PR DESCRIPTION
**Pull request by ataber**
Looking for other interesting things to add to the demo other than replication. I'm open to ideas!

### CODE REVIEW

**Comment by Erkaman** [comment]
Nice! But you need to be using the [standard style](https://github.com/feross/standard), or the tests won't pass, and you can't merge

You can verify whether it conforms to the standard style by running
```
npm run test
```
and if it starts running the unit tests, then it means that it passes the standard style checks.

**Comment by Erkaman** [comment]
As for suggestions for improvements: 

* It would be sweet if you could move the camera.
* You should consider using a full-screen triangle, instead of drawing a full-screen quad like you are doing right now. [See the life example](https://github.com/mikolalysenko/regl/blob/gh-pages/example/life.js). Full-screen triangles can have [performance advantages](https://github.com/mikolalysenko/a-big-triangle)
* Give the rendered objects different colors, sizes, and rotations and stuff, for more variation.

**Comment by Erkaman** [comment]
Do you consider your demo done now? You want me to do code-review and merge?

I answered your question about the fullscreen-triangle in the chat, but I will also copy the answer here for convenience:

No it will only draw one triangle, because the list is of length 6, and the corresponding input attribute is varying vec2 uv;. This means that every vertex is a vector of length 2. So the total number of vertices is 6/2 = 3, which is 3, which enough for a triangle.

**Comment by ataber** [comment]
I'm ready for a code review now! Thanks for your help

**Comment by Erkaman** [comment]
Everything looks fine to me. Merging in.

I will take care of rebuilding the gallery.

**Comment by Erkaman** [comment]
[Rebuilt Gallery](https://mikolalysenko.github.io/regl/www/gallery.html). Awesome work 👍

**Pull request merged**
