### PR TITLE
threejs spinning cube example

### PR DESCRIPTION
**Pull request by ahoskins**

### CODE REVIEW

**Comment by Erkaman** [comment]
This looks great! I will review it some, and then probably merge it. We may even be able to use this to compare the performance of regl and threejs.

**Comment by ahoskins** [comment]
Awesome. Regl really fascinates me, I just ran into it today. I'd be curious to compare performance.

**Comment by Erkaman** [comment]
The demo needs to be modified so that the camera moves exactly the same way as the other demos. This makes it easier to use for benchmarking comparisons.

But I will now take care of that. Merged.

**Comment by Erkaman** [comment]
I have normalized the demo now, with PR #147.

**Comment by Erkaman** [comment]
Now I have used your spinning cube demo to implement a benchmark that compares the performance of `regl` and `three.js`.
https://mikolalysenko.github.io/regl/www/bench.html
`cube` is using `regl`, and
`cube-threejs` is using `three.js`. As you can see, `regl` is much faster.

**Comment by ahoskins** [comment]
Nice.  It's worth mentioning that `three.js` does offer more efficient ways to implement things than I chose to do for the spinning cube example. Like: http://threejs.org/docs/api/core/BufferGeometry.html.

**Pull request merged**
