### PR TITLE
Add simple script to check missing npm dependencies

### PR DESCRIPTION
**Pull request by thammin**
Currently it check all `js` files except patterns in `.gitignore` and ignore list of `standard`
Refer to https://github.com/mikolalysenko/regl/pull/243

### CODE REVIEW

**Comment by mikolalysenko** [comment]
Cool!  Though maybe this script should be part of the test suite so it gets on CI.  Perhaps putting it in the test command would be better than in `build`?

**Comment by Erkaman** [comment]
Yeah, that would be great.

**Comment by thammin** [comment]
That makes sense, Lets moves it to the `test` command!

**Comment by mikolalysenko** [comment]
Thanks!  This is really helpful.

**Pull request merged**
