### PR TITLE
Add line mesh example

### PR DESCRIPTION
**Pull request by jpweeks**
Demonstrates screen space projected lines (from technique described in https://mattdesl.svbtle.com/drawing-lines-is-hard) and offset buffer attributes.

cc @mattdesl

### CODE REVIEW

**Comment by Erkaman** [comment]
Thank you. I shall review the example.

**Comment by Erkaman** [comment]
We are using [Standard JS](https://github.com/feross/standard) in this project. You need to write your code to conform to this, otherwise, it won't pass the tests on CircleCI. 

run 

```
npm run test
```

in the terminal, to see if it passes standard JS.

**Comment by Erkaman** [comment]
The code seems fine. However, I need you to also add a HTML-formatted description comment to the very beginning of the example. [Like this](https://github.com/mikolalysenko/regl/blob/gh-pages/example/planar-reflection.js).
This comment will show up as the description of the example in our [gallery](https://mikolalysenko.github.io/regl/www/gallery.html)

Fix that, and I will merge it in.

**Comment by Erkaman** [comment]
Merged

**Comment by mikolalysenko** [comment]
@jpweeks thanks!  This looks great!

**Comment by jpweeks** [comment]
Thanks! Was fun to write with `regl` 😄

**Pull request merged**
