### PR TITLE
Add Parallel Reduction Example

### PR DESCRIPTION
**Pull request by Erkaman**
Add example that implements parallel reduction on the GPU. 

screen shot 2016-08-05 at 21 52 07

### CODE REVIEW

**Comment by Erkaman** [comment]
demo: https://mikolalysenko.github.io/regl/www/gallery/reduction.js.html

**Comment by Erkaman** [comment]
This partially solves issue #164.

**Comment by freeman-lab** [comment]
This is awesome @Erkaman !

**Comment by mikolalysenko** [comment]
THIS IS RADICAL!

**Pull request merged**
